name: release

on:
    push:
        tags:
            - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
    publish:
        runs-on: ubuntu-latest
        name: Publish release
        steps:
            - uses: actions/checkout@v3
            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  registry-url: "https://registry.npmjs.org"
            - name: Publish GitHub release
              uses: eloquent/github-release-action@v3
              with:
                  prerelease: "false"
            - name: Publish npm release
              run: npm publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
