name: release

on:
    push:
        tags:
            - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
    publish:
        runs-on: ubuntu-latest
        name: Publish release
        steps:
            - uses: actions/checkout@v3
            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  registry-url: "https://registry.npmjs.org"
            - name: Publish node-fetch-cookies
              run: npm publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
